# Generated by Django 5.1.7 on 2025-03-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_course_assessments_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
