# Generated by Django 5.1.7 on 2025-03-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_team_course_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='course', to='assessments.team'),
        ),
    ]
