# Generated by Django 5.1.6 on 2025-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="self_assessment_required",
            field=models.BooleanField(default=False),
        ),
    ]
