# Generated by Django 5.1.7 on 2025-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessment_self_assessment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
    ]
