# Generated by Django 5.1.7 on 2025-04-15 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_peerassessment_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='assessments.course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.course'),
        ),
    ]
