# Generated by Django 5.1.7 on 2025-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_courseinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
