# Generated by Django 5.1.8 on 2025-04-16 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_assessment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='student',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('assessment', 'student')},
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
