# Generated by Django 5.1.8 on 2025-04-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_likertquestion_openendedquestion_likertresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
