# Generated by Django 5.1.8 on 2025-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_courseinvitation_enrollment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvitation',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
