# Generated by Django 5.1.7 on 2025-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_alter_courseinvitation_enrollment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
