# Generated by Django 5.1.7 on 2025-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_assessment_is_published_assessment_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
