# Generated by Django 5.1.7 on 2025-04-29 03:04

import assessments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def skip_if_table_exists(apps, schema_editor):
    # Check if the table already exists
    if 'assessments_submission' not in schema_editor.connection.introspection.table_names():
        # Only create the model if the table doesn't exist
        # Your original model creation code here
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_studentscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.RunPython(skip_if_table_exists, migrations.RunPython.noop),
    ]
