# Generated by Django 5.1.7 on 2025-04-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_alter_course_enrollment_code_submission'),
        ('assessments', '0024_alter_likertresponse_unique_together_and_more'),
    ]

    operations = [
    ]
