# Generated by Django 5.1.8 on 2025-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_merge_20250429_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvitation',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
