# Generated by Django 5.1.7 on 2025-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_alter_courseinvitation_enrollment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
