# Generated by Django 5.1.7 on 2025-05-06 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_remove_assessment_is_closed_assessment_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('assessment', 'student', 'assessed_peer')},
        ),
    ]
