# Generated by Django 5.1.7 on 2025-05-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_alter_assessmentsubmission_student'),
        ('assessments', '0032_convert_username_to_user'),
    ]

    operations = [
    ]
