# Generated by Django 5.1.7 on 2025-03-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_progress_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='progress_data',
            field=models.JSONField(default=dict),
        ),
    ]
