# Generated by Django 5.1.7 on 2025-03-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_assessmentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
