# Generated by Django 5.1.6 on 2025-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_userprofile_preferred_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentprogress",
            name="progress_notes",
            field=models.JSONField(default=dict),
        ),
    ]
