# Generated by Django 5.1.7 on 2025-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_assessmentprogress_progress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentprogress',
            name='progress_notes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
