import math
import random
import string
import time
from datetime import datetime, timedelta

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import connection, transaction
from django.db.models import Q
from django.utils import timezone

from assessments.models import (
    Assessment,
    Course,
    LikertQuestion,
    OpenEndedQuestion,
    Team,
)


LEVEL_CONFIG = {
    1: {
        "courses_per_semester": 120,
        "students_min": 25,
        "students_max": 60,
        "team_min": 3,
        "team_max": 7,
    },
    2: {
        "courses_per_semester": 600,
        "students_min": 30,
        "students_max": 75,
        "team_min": 4,
        "team_max": 6,
    },
    3: {
        "courses_per_semester": 1500,
        "students_min": 35,
        "students_max": 90,
        "team_min": 4,
        "team_max": 6,
    },
}


COURSE_TITLES = [
    "Software Engineering",
    "Data Structures",
    "Operating Systems",
    "Machine Learning",
    "Human Computer Interaction",
    "Algorithms",
    "Database Systems",
    "Networks",
    "Mobile App Development",
    "Artificial Intelligence",
]


ASSESSMENT_TITLES = [
    "Iteration Review",
    "Midterm Peer Feedback",
    "Final Project Evaluation",
    "Sprint Retrospective",
]


LIKERT_BANK = [
    "This teammate contributed fairly to the workload.",
    "This teammate communicated effectively.",
    "This teammate met agreed upon deadlines.",
    "I would choose to work with this teammate again.",
]


OPEN_ENDED_BANK = [
    "Describe one strength this teammate demonstrated.",
    "What is one area of improvement for this teammate?",
    "Provide any additional comments for this teammate.",
]


def random_course_name(index: int) -> str:
    base = random.choice(COURSE_TITLES)
    return f"{base} {index + 1}"


def random_description() -> str:
    topics = [
        "team-based projects",
        "weekly labs",
        "research presentations",
        "software prototypes",
        "iterative design",
        "case studies",
    ]
    return (
        f"This autogenerated course focuses on {random.choice(topics)} and "
        f"requires extensive collaboration between students."
    )


def random_enrollment_code() -> str:
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=8))


class Command(BaseCommand):
    help = (
        "Seed the database with realistic course, team, user, and assessment data.\n"
        "Usage: python manage.py seed_data --level 1 --semester Fall --year 2025"
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--level",
            type=int,
            choices=LEVEL_CONFIG.keys(),
            default=1,
            help="Data volume level to generate.",
        )
        parser.add_argument(
            "--semester",
            type=str,
            choices=["Spring", "Summer", "Fall"],
            default="Fall",
            help="Semester to stamp on generated courses.",
        )
        parser.add_argument(
            "--year",
            type=int,
            default=datetime.utcnow().year,
            help="Academic year for generated courses.",
        )
        parser.add_argument(
            "--seed",
            type=int,
            default=3364,
            help="Seed for the random number generator.",
        )
        parser.add_argument(
            "--fast-passwords",
            action="store_true",
            help="Assign unusable passwords instead of hashing real ones for speed.",
        )
        parser.add_argument(
            "--purge",
            action="store_true",
            help="Remove previously generated data before seeding new data.",
        )
        parser.add_argument(
            "--purge-only",
            action="store_true",
            help="Remove generated data and exit without creating new records.",
        )

    def handle(self, *args, **options):
        level = options["level"]
        semester = options["semester"]
        year = options["year"]
        seed = options["seed"]
        fast_passwords = options["fast_passwords"]
        purge = options["purge"]
        purge_only = options["purge_only"]

        random.seed(seed)

        if purge:
            self._purge_generated_data()
            if purge_only:
                return

        config = LEVEL_CONFIG[level]
        courses_target = config["courses_per_semester"]
        students_min = config["students_min"]
        students_max = config["students_max"]
        team_min = config["team_min"]
        team_max = config["team_max"]

        self.stdout.write(
            self.style.NOTICE(
                f"Generating level {level} dataset: ~{courses_target} courses for {semester} {year}"
            )
        )

        User = get_user_model()

        created_courses = 0
        created_professors = 0
        created_students = 0
        created_teams = 0
        created_assessments = 0

        username_counter = random.randint(1000, 9000)
        email_domain = "seeded.example.edu"

        start = time.time()
        progress_every = max(1, courses_target // 20)

        for course_index in range(courses_target):
            with transaction.atomic():
                course_code = f"AUTO{year}{course_index:04d}"
                course_title = random_course_name(course_index)

                professor_username = f"prof_{username_counter}"
                username_counter += 1

                professor = User.objects.create(
                    username=professor_username,
                    email=f"{professor_username}@{email_domain}",
                    first_name="Prof",
                    last_name=str(course_index + 1),
                )
                if fast_passwords:
                    professor.set_unusable_password()
                else:
                    professor.set_password("Passw0rd!")
                professor.save()
                if hasattr(professor, "profile"):
                    professor.profile.role = "professor"
                    professor.profile.save(update_fields=["role"])
                created_professors += 1

                course = Course.objects.create(
                    name=course_title,
                    course_code=course_code,
                    year=str(year),
                    semester=semester,
                    description=random_description(),
                    created_by=professor,
                    enrollment_code=random_enrollment_code(),
                )
                created_courses += 1

                student_count = random.randint(students_min, students_max)
                students_for_course = []
                for _ in range(student_count):
                    student_username = f"student_{username_counter}"
                    username_counter += 1
                    student = User.objects.create(
                        username=student_username,
                        email=f"{student_username}@{email_domain}",
                        first_name=random.choice(["Alex", "Jordan", "Taylor", "Morgan", "Riley", "Casey"]),
                        last_name=random.choice(["Lee", "Patel", "Chen", "Garcia", "Kim", "Nguyen"]),
                    )
                    if fast_passwords:
                        student.set_unusable_password()
                    else:
                        student.set_password("Passw0rd!")
                    student.save()
                    if hasattr(student, "profile"):
                        student.profile.role = "student"
                        student.profile.save(update_fields=["role"])
                    students_for_course.append(student)
                    created_students += 1

                course.students.add(*students_for_course)

                preferred_team_size = random.randint(team_min, team_max)
                random.shuffle(students_for_course)
                teams_needed = max(1, math.ceil(len(students_for_course) / preferred_team_size))

                teams = []
                for team_number in range(teams_needed):
                    team = Team.objects.create(
                        name=f"Team {team_number + 1}",
                        course=course,
                        is_active=True,
                    )
                    teams.append(team)
                    created_teams += 1

                for idx, student in enumerate(students_for_course):
                    team = teams[idx % teams_needed]
                    team.members.add(student)

                assessment_title = f"Auto {random.choice(ASSESSMENT_TITLES)}"
                assessment = Assessment.objects.create(
                    title=assessment_title,
                    course=course,
                    description="Autogenerated assessment for load testing.",
                    open_date=timezone.now() - timedelta(days=7),
                    due_date=timezone.now() + timedelta(days=7),
                    published=True,
                )
                created_assessments += 1

                for order, question_text in enumerate(random.sample(LIKERT_BANK, k=len(LIKERT_BANK))):
                    LikertQuestion.objects.create(
                        assessment=assessment,
                        question_text=question_text,
                        order=order,
                        question_type="team",
                    )

                for order, question_text in enumerate(random.sample(OPEN_ENDED_BANK, k=len(OPEN_ENDED_BANK))):
                    OpenEndedQuestion.objects.create(
                        assessment=assessment,
                        question_text=question_text,
                        order=order,
                        question_type="team",
                    )

            if (course_index + 1) % progress_every == 0 or (course_index + 1) == courses_target:
                elapsed = time.time() - start
                pct = ((course_index + 1) / courses_target) * 100
                self.stdout.write(
                    self.style.NOTICE(
                        f"Progress: {course_index + 1}/{courses_target} courses ({pct:0.1f}%) in {elapsed:0.1f}s"
                    )
                )

        total_elapsed = time.time() - start
        self.stdout.write(
            self.style.SUCCESS(
                "Created "
                f"{created_courses} courses, {created_professors} professors, {created_students} students, "
                f"{created_teams} teams, {created_assessments} assessments in {total_elapsed:0.1f}s"
            )
        )

    def _purge_generated_data(self):
        User = get_user_model()
        self.stdout.write(self.style.WARNING("Purging previously generated data..."))

        existing_tables = set(connection.introspection.table_names())
        if Course._meta.db_table not in existing_tables:
            self.stdout.write("Database tables have not been created yet; skipping purge.")
            return

        generated_courses = Course.objects.filter(course_code__startswith="AUTO")
        course_total = generated_courses.count()
        generated_courses.delete()
        self.stdout.write(f"Deleted {course_total} autogenerated courses (and dependent objects).")

        generated_assessments = Assessment.objects.filter(title__startswith="Auto ")
        assess_total = generated_assessments.count()
        generated_assessments.delete()
        self.stdout.write(f"Deleted {assess_total} autogenerated assessments.")

        generated_users = User.objects.filter(
            Q(username__startswith="prof_") | Q(username__startswith="student_")
        )
        user_total = generated_users.count()
        generated_users.delete()
        self.stdout.write(f"Deleted {user_total} autogenerated users.")

        self.stdout.write(self.style.SUCCESS("Purge complete."))